apiVersion: v1
kind: Service
metadata:
  labels:
    app: "{{ .Release.Name }}"
  name: "{{ .Release.Name }}-ui-ext"
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  - name: https
    port: 443
    protocol: TCP
    targetPort: 443
  selector:
    app: "{{ .Release.Name }}"
    component: console
  type: NodePort