---
platform: linux
inputs:
- name: stratos-ui
- name: helm-chart-Chart
- name: helm-chart-values
outputs:
- name: helm-chart
image_resource:
  type: docker-image
  source:
   repository:  ci-registry.ngrok.io:80/helm-deploy
   tag: "latest"
   insecure_registries: [ "ci-registry.ngrok.io:80" ]

run:
  path: sh
  args:
    - -exc
    - |
      mkdir ~/.kube
      wget ${CAASP_KUBE_CONFIG_URL} -O ~/.kube/config

      kubectl cluster-info
      helm init || true
      
      ROOT_DIR=$PWD
      STRATOS_UI=${ROOT_DIR}/stratos-ui
      cd ${STRATOS_UI}/deploy/kubernetes/

      cp -f ${ROOT_DIR}/helm-chart-values/values.yaml-helm-nightly console/values.yaml
      cp -f ${ROOT_DIR}/helm-chart-Chart/Chart.yaml-helm-nightly console/Chart.yaml
      helm dep build console

      helm install console --set storageClass=hostpath --set mariadb.persistence.storageClass=hostpath --namespace nightly-test --name console
      sleep 120

      helm list
      kubectl get po --all-namespaces

      helm delete console-nightly --purge