---
platform: linux
inputs:
- name: stratos-ui
image_resource:
  type: docker-image
  source:
   repository: registry.capbristol.com:5000/portal-proxy-test
   tag: "latest"
   insecure_registries: [ "registry.capbristol.com:5000" ]

run:
  path: sh
  args:
    - -exc
    - |
      cd stratos-ui
      if [ "${SET_PROXIES}" = "true" ]; then
      export http_proxy=${PROXY_SERVER}
      export https_proxy=${PROXY_SERVER}
      npm config set proxy  ${PROXY_SERVER}
      npm config set https-proxy  ${PROXY_SERVER}
      fi
      npm install
      npm run test-backend