---
platform: linux
inputs:
- name: stratos-ui
image_resource:
  type: docker-image
  source:
   repository: registry.capbristol.com:5000/portal-proxy-test
   tag: "latest"
   insecure_registries: [ "registry.capbristol.com:5000" ]

run:
  path: sh
  args:
    - -exc
    - |
      cd stratos-ui
      export http_proxy=http://registry.capbristol.com:8080
      export https_proxy=http://registry.capbristol.com:8080
      npm config set proxy http://registry.capbristol.com:8080
      npm config set https-proxy http:///registry.capbristol.com:8080
      npm install
      npm run test-backend