resource_types:
  - name: email
    type: docker-image
    source:
      repository: pcfseceng/email-resource
resources:
- name: stratos-ui
  type: git
  source:
    branch: {{stratos-ui-branch}}
    private_key: {{github-private-key}}
    uri: git@github.com:SUSE/stratos-ui.git
- name: after-midnight
  type: time
  source:
    start: 12:00 AM
    stop: 2:00 AM
    location: UTC
- name: send-email
  type: email
  source:
    smtp:
      host: {{email-server}}
      port: {{email-port}}
      username: {{email-username}}
      password: {{email-password}}
    from: {{email-from}}
    to: [ ]
jobs:
- name: console-bosh-deploy
  plan:
  - get: stratos-ui
  - get: after-midnight
    trigger: true
  - do:
    - task: deploy
      privileged: true
      timeout: 20m
      file:  stratos-ui/deploy/ci/tasks/bosh/compile.yml
      params:
       BOSH_DIRECTOR_IP: {{bosh-director-ip}}
       BOSH_CA_CERT: {{bosh-ca-cert}}
       BOSH_ADMIN_PASSWORD: {{bosh-admin-password}}
       UAA_ADMIN_PASSWORD: {{uaa-admin-password}}
       UAA_ADMIN_USERNAME: {{uaa-admin-username}}
       UAA_CLIENT_ID: {{uaa-client-id}}
       UAA_URL: {{uaa-url}}
       CF_LOCATION: {{cf-location}}
       CF_ADMIN_USER: {{cf-admin-user}}
       CF_ADMIN_PASSWORD: {{cf-admin-password}}
       CF_E2E_USER: {{cf-e2e-user}}
       CF_E2E_USER_PASSWORD: {{cf-e2e-user-password}}
       CONSOLE_ADMIN_USER: {{console-admin-user}}
       CONSOLE_ADMIN_PASSWORD: {{console-admin-password}}
       CONSOLE_USER_USER: {{console-user-user}}
       CONSOLE_USER_PASSWORD: {{console-user-password}}
       GITHUB_TOKEN: {{github-access-token}}
      on_failure:
        put: send-email
        params:
          subject_text: "BOSH Deploy ${BUILD_PIPELINE_NAME}/${BUILD_JOB_NAME}/${BUILD_NAME} failed!"
          body_text: "BOSH Deploy build was failed: ${ATC_EXTERNAL_URL}/teams/main/pipelines/${BUILD_PIPELINE_NAME}/jobs/${BUILD_JOB_NAME}/builds/${BUILD_NAME}"
      on_success:
        put: send-email
        params:
          subject_text: "BOSH Deploy ${BUILD_PIPELINE_NAME}/${BUILD_JOB_NAME}/${BUILD_NAME} successful"
          body_text: "BOSH Deploy build was successful: ${ATC_EXTERNAL_URL}/teams/main/pipelines/${BUILD_PIPELINE_NAME}/jobs/${BUILD_JOB_NAME}/builds/${BUILD_NAME}"
 
