version: '2'
services:

  prometheus:
      image: prom/prometheus
      volumes:
        - ./prometheus.yml:/etc/prometheus/prometheus.yml
      ports:
        - 9095:9090


  firehose_nozzle:
      image: cfcommunity/firehose-exporter
      env_file:
        - ./firehose.env


  grafana:
      image: grafana/grafana
      ports:
        - 3005:3000